title: PL Conference Deadlines
description: Countdowns to top PL conference deadlines
author: Wota-tachi

domain: "reikdas.github.io"
baseurl: "/yeah-tiger"

github_username: reikdas
github_repo: yeah-tiger

markdown: kramdown

include: ['_pages']
