title: PL Conference Deadlines
description: Countdowns to top PL conference deadlines
author: Wota-tachi

domain: "reikdas.github.io"
baseurl: "/yeah-tiger"

github_username: yeah-tiger
github_repo: yeah-tiger.github.io

markdown: kramdown

include: ['_pages']
